# Generated by Django 5.1.2 on 2024-10-27 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientData",
            fields=[
                (
                    "trauma_register_record_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "direccion_linea_1",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "direccion_linea_2",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "ciudad",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "canton_municipio",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "provincia_estado",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "codigo_postal",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "pais",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                ("edad", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "unidad_de_edad",
                    models.CharField(blank=True, default=None, max_length=9, null=True),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "fecha_de_nacimiento",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "ocupacion",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "nacionalidad",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "grupo_etnico",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                (
                    "otro_grupo_etnico",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                (
                    "num_doc_de_identificacion",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
            ],
            options={
                "db_table": "patient_data",
            },
        ),
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resultado_de_laboratorio",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "fecha_y_hora_de_laboratorio",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "nombre_del_laboratorio",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "nombre_de_la_unidad_de_laboratorio",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "laboratory",
            },
        ),
        migrations.CreateModel(
            name="IntensiveCareUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "fecha_y_hora_de_inicio",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "fecha_y_hora_de_termino",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "lugar",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "icu_days",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "intensive_care_unit",
            },
        ),
        migrations.CreateModel(
            name="InjuryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consumo_de_alcohol",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "valor_de_alcoholemia",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "unidad_de_alcohol",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                (
                    "otra_sustancia_de_abuso",
                    models.CharField(
                        blank=True, default=None, max_length=600, null=True
                    ),
                ),
                (
                    "direccion_nombre_del_lugar",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "ciudad_de_evento_de_la_lesion",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                (
                    "condado_de_lesiones",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                (
                    "estado_provincia_de_lesiones",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                (
                    "pais_de_lesiones",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                (
                    "codigo_postal_de_lesiones",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                (
                    "fecha_y_hora_del_evento",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "accidente_de_trafico",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "tipo_de_vehiculo",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "ocupante",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                (
                    "velocidad_de_colision",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                ("scq", models.SmallIntegerField(blank=True, default=None, null=True)),
                ("caida", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "altura_metros",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "tipo_de_superficie",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "injury_record",
            },
        ),
        migrations.CreateModel(
            name="Imaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_de_imagen",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "parte_del_cuerpo",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                ("opcion", models.BooleanField(blank=True, default=None, null=True)),
                ("descripcion", models.TextField(blank=True, default=None, null=True)),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "imaging",
            },
        ),
        migrations.CreateModel(
            name="HospitalizationVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_de_variable",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "valor_de_la_variable",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "fecha_y_hora_de_la_variable",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "localizacion_de_variable",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "hospitalization_variable",
            },
        ),
        migrations.CreateModel(
            name="HospitalizationComplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_de_complicacion",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "fecha_y_hora_de_complicacion",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "lugar_de_complicacion",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "hospitalization_complication",
            },
        ),
        migrations.CreateModel(
            name="HealthcareRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_de_historia_clinica",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "hospital",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "fecha_y_hora_de_llegada_del_paciente",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("referido", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "policia_notificada",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "fecha_y_hora_de_llegada_del_medico",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "fecha_y_hora_de_notificacion_al_medico",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "alerta_equipo_de_trauma",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "nivel_de_alerta",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "paciente_asegurado",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "tipo_de_seguro",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                (
                    "motivo_de_consulta",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "inmunizacion_contra_el_tetanos",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                (
                    "descripcion_del_examen_fisico",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "mecanismo_primario",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "numero_de_lesiones_serias",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "descripcion_del_diagnostico",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "disposicion_o_destino_del_paciente",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "donacion_de_organos",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "autopsia",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "muerte_prevenible",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "tipo_de_admision",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "fecha_y_hora_de_la_disposicion",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "tiempo_en_sala_de_emergencias_hora",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "tiempo_en_sala_de_emergencias_minutos",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "numero_de_referencia_del_ed",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "fecha_de_admision",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "fecha_y_hora_de_alta",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "dias_de_hospitalizacion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("uci_dias", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "detalles_de_hospitalizacion",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "disposicion_o_destino_del_paciente_del_hospitalizacion",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "donacion_de_organos_del_hospitalizacion",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "autopsia_del_hospitalizacion",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "muerte_prevenible_del_hospitalizacion",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "numero_de_referencia_del_hospitalizacion",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "agencia_de_transporte",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "origen_del_transporte",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "numero_de_registro_del_transporte",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "fecha_y_hora_de_notificacion_pre_hospitalaria",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "fecha_y_hora_de_llegada_a_la_escena",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "fecha_y_hora_de_salida_de_la_escena",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "razon_de_la_demora",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "reporte_o_formulario_pre_hospitalario_entregado",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "ciudad_hospital_mas_cercano_al_sitio_del_incidente",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "tiempo_de_extricacion_hora",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "tiempo_de_extricacion_minutos",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "duracion_del_transporte_horas",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "duracion_del_transporte_minutos",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "procedimiento_realizado",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "frecuencia_cardiaca_en_la_escena",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "presion_arterial_sistolica_en_la_escena",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "presion_arterial_diastolica_en_la_escena",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "frecuencia_respiratoria_en_la_escena",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "calificador_de_frecuencia_respiratoria_en_la_escena",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                (
                    "temperatura_en_la_escena_celsius",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "saturacion_de_o2_en_la_escena",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "frecuencia_cardiaca_durante_el_transporte",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "presion_arterial_sistolica_de_transporte",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "presion_diastolica_durante_el_transporte",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "frecuencia_respiratoria_durante_el_transporte",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "calificador_de_frecuencia_respiratoria_durante_el_transporte",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                (
                    "temperatura_durante_el_transporte_celsius",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "saturacion_de_o2_durante_el_transporte",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "perdida_de_conciencia",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "duracion_de_perdida_de_conciencia",
                    models.TimeField(blank=True, default=None, null=True),
                ),
                (
                    "gcs_ocular",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "gcs_verbal",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "gcs_motora",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "gcs_total",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "sangre_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        default=None,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "coloides_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        default=None,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "cristaloides_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        default=None,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "hallazgos_clinicos_texto",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "fecha_y_hora_de_envio_de_contra_referencia",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "fecha_de_alta_de_contrar_referencia",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "hallazgos_clinicos_existencia",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "servicio_que_atendio",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "paciente_admitido",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "hospital_que_recibe",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "otro_servicio",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "servicio_que_recibe",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "recomendaciones",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "numero_de_referencia_de_referencias_salientes",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "fecha_de_envio_de_referencia",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "fecha_de_referencia",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "razon_de_la_referencia",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "medico_que_refiere",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "estado_de_referencia",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "fecha_de_aceptacion_de_referencia",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("iss", models.SmallIntegerField(blank=True, default=None, null=True)),
                ("kts", models.SmallIntegerField(blank=True, default=None, null=True)),
                (
                    "rts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=None,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "abdomen",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "torax",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "externo",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "extremidades",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                ("cara", models.SmallIntegerField(blank=True, default=None, null=True)),
                (
                    "cabeza",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "triss_contuso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        default=None,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "triss_penetrante",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        default=None,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "healthcare_record",
            },
        ),
        migrations.CreateModel(
            name="FirearmInjury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_de_arma_de_fuego",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "firearm_injury",
            },
        ),
        migrations.CreateModel(
            name="DrugAbuse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_de_droga",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "drug_abuse",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_de_dispositivo",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "device",
            },
        ),
        migrations.CreateModel(
            name="Collision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_de_colision",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "collision",
            },
        ),
        migrations.CreateModel(
            name="BurnInjury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_de_quemadura",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "grado_de_quemadura",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "burn_injury",
            },
        ),
        migrations.CreateModel(
            name="ApparentIntentInjury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intencion_aparente",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "apparent_intent_injury",
            },
        ),
        migrations.CreateModel(
            name="PenetratingInjury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_de_lesion_penetrante",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "penetrating_injury",
            },
        ),
        migrations.CreateModel(
            name="PhysicalExamBodyPartInjury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parte_del_cuerpo",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "tipo_de_lesion",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "physical_exam_body_part_injury",
            },
        ),
        migrations.CreateModel(
            name="PoisoningInjury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_de_envenenamiento",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "poisoning_injury",
            },
        ),
        migrations.CreateModel(
            name="PrehospitalProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "procedimiento_realizado",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "prehospital_procedure",
            },
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "procedimiento_realizado",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "fecha_y_hora_de_inicio",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "fecha_y_hora_de_termino",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "lugar",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "procedure",
            },
        ),
        migrations.CreateModel(
            name="TransportationMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modo_de_transporte",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "transportation_mode",
            },
        ),
        migrations.CreateModel(
            name="TraumaRegisterIcd10",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField(blank=True, default=None, null=True)),
                (
                    "mecanismo_icd",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "trauma_register_icd10",
            },
        ),
        migrations.CreateModel(
            name="ViolenceInjury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_de_violencia",
                    models.CharField(
                        blank=True, default=None, max_length=90, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "violence_injury",
            },
        ),
        migrations.CreateModel(
            name="VitalSign",
            fields=[
                (
                    "record_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "fecha_y_hora_de_signos_vitales",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "signos_de_vida",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "frecuencia_cardiaca",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "presion_arterial_sistolica",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "presion_arterial_diastolica",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "frecuencia_respiratoria",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "calificador_de_frecuencia_respiratoria",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                (
                    "temperatura_celsius",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "peso_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "altura_metros",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "saturacion_de_oxigeno",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "perdida_de_conciencia",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "duracion_de_perdida_de_conciencia",
                    models.TimeField(blank=True, default=None, null=True),
                ),
                (
                    "gcs_motora",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "gcs_ocular",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "gcs_verbal",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "gcs_total",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "avup",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "vital_sign",
            },
        ),
        migrations.CreateModel(
            name="VitalSignGcsQualifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calificador_gcs",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "trauma_register_record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.patientdata",
                    ),
                ),
            ],
            options={
                "db_table": "vital_sign_gcs_qualifier",
            },
        ),
    ]
