# Generated by Django 5.1.2 on 2024-10-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientdata",
            name="fecha_de_nacimiento",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="patientdata",
            name="trauma_register_record_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
