# Generated by Django 5.1.2 on 2024-11-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientdata",
            name="trauma_register_record_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
