# Generated by Django 5.1.2 on 2024-12-11 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0002_alter_patientdata_trauma_register_record_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="healthcarerecord",
            old_name="tiempo_de_extricacion_hora",
            new_name="tiempo_de_extricacion_horas",
        ),
        migrations.RenameField(
            model_name="healthcarerecord",
            old_name="tiempo_en_sala_de_emergencias_hora",
            new_name="tiempo_en_sala_de_emergencias_horas",
        ),
    ]
