# Generated by Django 5.1.2 on 2025-03-06 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_rename_tiempo_de_extricacion_hora_healthcarerecord_tiempo_de_extricacion_horas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcarerecord',
            name='trauma_register_record_id',
            field=models.OneToOneField(db_column='trauma_register_record_id', on_delete=django.db.models.deletion.CASCADE, related_name='healthcare_record', to='medical_records.patientdata'),
        ),
        migrations.AlterField(
            model_name='injuryrecord',
            name='trauma_register_record_id',
            field=models.OneToOneField(db_column='trauma_register_record_id', on_delete=django.db.models.deletion.CASCADE, related_name='injury_record', to='medical_records.patientdata'),
        ),
    ]
