# Generated by Django 5.1.2 on 2024-11-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medical_records",
            "0003_alter_apparentintentinjury_trauma_register_record_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalsign",
            name="saturacion_de_oxigeno",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=4, null=True
            ),
        ),
    ]
