# Generated by Django 5.1.2 on 2024-11-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0004_alter_vitalsign_saturacion_de_oxigeno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcarerecord",
            name="coloides_l",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=None, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="healthcarerecord",
            name="cristaloides_l",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=None, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="healthcarerecord",
            name="sangre_l",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=None, max_digits=6, null=True
            ),
        ),
    ]
