# Generated by Django 5.1.2 on 2024-11-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0005_alter_healthcarerecord_coloides_l_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcarerecord",
            name="coloides_l",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=None,
                error_messages={
                    "invalid": {
                        "code": "invalid_value",
                        "message": 'The attribute called "coloides_l" isn\'t valid because the value is overflowing',
                    }
                },
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthcarerecord",
            name="cristaloides_l",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=None,
                error_messages={
                    "invalid": {
                        "code": "invalid_value",
                        "message": 'The attribute called "cristaloides_l" isn\'t valid because the value is overflowing',
                    }
                },
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthcarerecord",
            name="dias_de_hospitalizacion",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                error_messages={
                    "invalid": {
                        "code": "invalid_value",
                        "message": 'The attribute called "dias_de_hospitalizacion" isn\'t valid because the value is overflowing',
                    }
                },
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthcarerecord",
            name="rts",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=None,
                error_messages={
                    "invalid": {
                        "code": "invalid_value",
                        "message": 'The attribute called "rts" isn\'t valid because the value is overflowing',
                    }
                },
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthcarerecord",
            name="sangre_l",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=None,
                error_messages={
                    "invalid": {
                        "code": "invalid_value",
                        "message": 'The attribute called "sangre_l" isn\'t valid because the value is overflowing',
                    }
                },
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthcarerecord",
            name="temperatura_durante_el_transporte_celsius",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                error_messages={
                    "invalid": {
                        "code": "invalid_value",
                        "message": 'The attribute called "temperatura_durante_el_transporte_celsius" isn\'t valid because the value is overflowing',
                    }
                },
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthcarerecord",
            name="temperatura_en_la_escena_celsius",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                error_messages={
                    "invalid": {
                        "code": "invalid_value",
                        "message": 'The attribute called "temperatura_en_la_escena_celsius" isn\'t valid because the value is overflowing',
                    }
                },
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthcarerecord",
            name="triss_contuso",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                default=None,
                error_messages={
                    "invalid": {
                        "code": "invalid_value",
                        "message": 'The attribute called "triss_contuso" isn\'t valid because the value is overflowing',
                    }
                },
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthcarerecord",
            name="triss_penetrante",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                default=None,
                error_messages={
                    "invalid": {
                        "code": "invalid_value",
                        "message": 'The attribute called "triss_penetrante" isn\'t valid because the value is overflowing',
                    }
                },
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="injuryrecord",
            name="altura_metros",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                error_messages={
                    "invalid": {
                        "code": "invalid_value",
                        "message": 'The attribute called "altura_metros" isn\'t valid because the value is overflowing',
                    }
                },
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="injuryrecord",
            name="valor_de_alcoholemia",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                error_messages={
                    "invalid": {
                        "code": "invalid_value",
                        "message": 'The attribute called "valor_de_alcoholemia" isn\'t valid because the value is overflowing',
                    }
                },
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="intensivecareunit",
            name="icu_days",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                error_messages={
                    "invalid": {
                        "code": "invalid_value",
                        "message": 'The attribute called "icu_days" isn\'t valid because the value is overflowing',
                    }
                },
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patientdata",
            name="trauma_register_record_id",
            field=models.BigIntegerField(
                primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="altura_metros",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                error_messages={
                    "invalid": {
                        "code": "invalid_value",
                        "message": 'The attribute called "altura_metros" isn\'t valid because the value is overflowing',
                    }
                },
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="peso_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                error_messages={
                    "invalid": {
                        "code": "invalid_value",
                        "message": 'The attribute called "peso_kg" isn\'t valid because the value is overflowing',
                    }
                },
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="saturacion_de_oxigeno",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                error_messages={
                    "invalid": {
                        "code": "invalid_value",
                        "message": 'The attribute called "saturacion_de_oxigeno" isn\'t valid because the value is overflowing',
                    }
                },
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="temperatura_celsius",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                error_messages={
                    "invalid": {
                        "code": "invalid_value",
                        "message": 'The attribute called "temperatura_celsius" isn\'t valid because the value is overflowing',
                    }
                },
                max_digits=4,
                null=True,
            ),
        ),
    ]
