# Generated by Django 5.1.2 on 2024-11-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0006_alter_healthcarerecord_coloides_l_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcarerecord",
            name="coloides_l",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=None, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="healthcarerecord",
            name="cristaloides_l",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=None, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="healthcarerecord",
            name="dias_de_hospitalizacion",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="healthcarerecord",
            name="rts",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=None, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="healthcarerecord",
            name="sangre_l",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=None, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="healthcarerecord",
            name="temperatura_durante_el_transporte_celsius",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="healthcarerecord",
            name="temperatura_en_la_escena_celsius",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="healthcarerecord",
            name="triss_contuso",
            field=models.DecimalField(
                blank=True, decimal_places=5, default=None, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="healthcarerecord",
            name="triss_penetrante",
            field=models.DecimalField(
                blank=True, decimal_places=5, default=None, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="injuryrecord",
            name="altura_metros",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="injuryrecord",
            name="valor_de_alcoholemia",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="intensivecareunit",
            name="icu_days",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="altura_metros",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="peso_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="saturacion_de_oxigeno",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="temperatura_celsius",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=4, null=True
            ),
        ),
    ]
