from rest_framework.routers import DefaultRouter
from .views import PatientDataViewsets, HealthcareRecordViewsets, InjuryRecordViewsets, CollisionViewsets, DrugAbuseViewsets, VitalSignGcsQualifierViewsets, HospitalizationVariableViewsets, HospitalizationComplicationViewsets, TraumaRegisterIcd10Viewsets, IntensiveCareUnitViewsets, ImagingViewsets, ApparentIntentInjuryViewsets, BurnInjuryViewsets, FirearmInjuryViewsets, PenetratingInjuryViewsets, PoisoningInjuryViewsets, ViolenceInjuryViewsets, DeviceViewsets, LaboratoryViewsets, PhysicalExamBodyPartInjuryViewsets, ProcedureViewsets, PrehospitalProcedureViewsets, TransportationModeViewsets, VitalSignViewsets
router = DefaultRouter()

router.register(r'patient-data', PatientDataViewsets, basename='patient-data')
router.register(r'healthcare-record', HealthcareRecordViewsets, basename='healthcare-record')
router.register(r'injury-record', InjuryRecordViewsets, basename='injury-record')
router.register(r'collision', CollisionViewsets, basename='collision')
router.register(r'drug-abuse', DrugAbuseViewsets, basename='drug-abuse')
router.register(r'vital-sign-gcs-qualifier', VitalSignGcsQualifierViewsets, basename='vital-sign-gcs-qualifier')
router.register(r'hospitalization-variable', HospitalizationVariableViewsets, basename='hospitalization-variable')
router.register(r'hospitalization-complication', HospitalizationComplicationViewsets, basename='hospitalization-complication')
router.register(r'trauma-register-icd10', TraumaRegisterIcd10Viewsets, basename='trauma-register-icd10')
router.register(r'intensive-care-unit', IntensiveCareUnitViewsets, basename='intensive-care-unit')
router.register(r'imaging', ImagingViewsets, basename='imaging')
router.register(r'apparent-intent-injury', ApparentIntentInjuryViewsets, basename='apparent-intent-injury')
router.register(r'burn-injury', BurnInjuryViewsets, basename='burn-injury')
router.register(r'firearm-injury', FirearmInjuryViewsets, basename='firearm-injury')
router.register(r'penetrating-injury', PenetratingInjuryViewsets, basename='penetrating-injury')
router.register(r'poisoning-injury', PoisoningInjuryViewsets, basename='poisoning-injury')
router.register(r'violence-injury', ViolenceInjuryViewsets, basename='violence-injury')
router.register(r'device', DeviceViewsets, basename='device')
router.register(r'laboratory', LaboratoryViewsets, basename='laboratory')
router.register(r'physical-exam-body-part-injury', PhysicalExamBodyPartInjuryViewsets, basename='physical-exam-body-part-injury')
router.register(r'procedure', ProcedureViewsets, basename='procedure')
router.register(r'prehospital-procedure', PrehospitalProcedureViewsets, basename='prehospital-procedure')
router.register(r'transportation-mode', TransportationModeViewsets, basename='transportation-mode')
router.register(r'vital-sign', VitalSignViewsets, basename='vital-sign')

urlpatterns = router.urls